// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/echo/echo.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ChargeRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ChargeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChargeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ChargeRequestMultiError, or
// nil if none found.
func (m *ChargeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ChargeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ChargeRequestMultiError(errors)
	}

	return nil
}

// ChargeRequestMultiError is an error wrapping multiple validation errors
// returned by ChargeRequest.ValidateAll() if the designated constraints
// aren't met.
type ChargeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChargeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChargeRequestMultiError) AllErrors() []error { return m }

// ChargeRequestValidationError is the validation error returned by
// ChargeRequest.Validate if the designated constraints aren't met.
type ChargeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChargeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChargeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChargeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChargeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChargeRequestValidationError) ErrorName() string { return "ChargeRequestValidationError" }

// Error satisfies the builtin error interface
func (e ChargeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChargeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChargeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChargeRequestValidationError{}

// Validate checks the field values on ChargeResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ChargeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChargeResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ChargeResponseMultiError,
// or nil if none found.
func (m *ChargeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ChargeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ChargeResponseMultiError(errors)
	}

	return nil
}

// ChargeResponseMultiError is an error wrapping multiple validation errors
// returned by ChargeResponse.ValidateAll() if the designated constraints
// aren't met.
type ChargeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChargeResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChargeResponseMultiError) AllErrors() []error { return m }

// ChargeResponseValidationError is the validation error returned by
// ChargeResponse.Validate if the designated constraints aren't met.
type ChargeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChargeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChargeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChargeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChargeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChargeResponseValidationError) ErrorName() string { return "ChargeResponseValidationError" }

// Error satisfies the builtin error interface
func (e ChargeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChargeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChargeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChargeResponseValidationError{}

// Validate checks the field values on DischargeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DischargeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DischargeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DischargeRequestMultiError, or nil if none found.
func (m *DischargeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DischargeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DischargeRequestMultiError(errors)
	}

	return nil
}

// DischargeRequestMultiError is an error wrapping multiple validation errors
// returned by DischargeRequest.ValidateAll() if the designated constraints
// aren't met.
type DischargeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DischargeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DischargeRequestMultiError) AllErrors() []error { return m }

// DischargeRequestValidationError is the validation error returned by
// DischargeRequest.Validate if the designated constraints aren't met.
type DischargeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DischargeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DischargeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DischargeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DischargeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DischargeRequestValidationError) ErrorName() string { return "DischargeRequestValidationError" }

// Error satisfies the builtin error interface
func (e DischargeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDischargeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DischargeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DischargeRequestValidationError{}

// Validate checks the field values on DischargeResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *DischargeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DischargeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DischargeResponseMultiError, or nil if none found.
func (m *DischargeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DischargeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DischargeResponseMultiError(errors)
	}

	return nil
}

// DischargeResponseMultiError is an error wrapping multiple validation errors
// returned by DischargeResponse.ValidateAll() if the designated constraints
// aren't met.
type DischargeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DischargeResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DischargeResponseMultiError) AllErrors() []error { return m }

// DischargeResponseValidationError is the validation error returned by
// DischargeResponse.Validate if the designated constraints aren't met.
type DischargeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DischargeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DischargeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DischargeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DischargeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DischargeResponseValidationError) ErrorName() string {
	return "DischargeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DischargeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDischargeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DischargeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DischargeResponseValidationError{}
