// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/echo/echo.proto

package api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChargeRequest) Reset() {
	*x = ChargeRequest{}
	mi := &file_proto_echo_echo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeRequest) ProtoMessage() {}

func (x *ChargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_echo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeRequest.ProtoReflect.Descriptor instead.
func (*ChargeRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_echo_proto_rawDescGZIP(), []int{0}
}

type ChargeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChargeResponse) Reset() {
	*x = ChargeResponse{}
	mi := &file_proto_echo_echo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeResponse) ProtoMessage() {}

func (x *ChargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_echo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeResponse.ProtoReflect.Descriptor instead.
func (*ChargeResponse) Descriptor() ([]byte, []int) {
	return file_proto_echo_echo_proto_rawDescGZIP(), []int{1}
}

type DischargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DischargeRequest) Reset() {
	*x = DischargeRequest{}
	mi := &file_proto_echo_echo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DischargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DischargeRequest) ProtoMessage() {}

func (x *DischargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_echo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DischargeRequest.ProtoReflect.Descriptor instead.
func (*DischargeRequest) Descriptor() ([]byte, []int) {
	return file_proto_echo_echo_proto_rawDescGZIP(), []int{2}
}

type DischargeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DischargeResponse) Reset() {
	*x = DischargeResponse{}
	mi := &file_proto_echo_echo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DischargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DischargeResponse) ProtoMessage() {}

func (x *DischargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_echo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DischargeResponse.ProtoReflect.Descriptor instead.
func (*DischargeResponse) Descriptor() ([]byte, []int) {
	return file_proto_echo_echo_proto_rawDescGZIP(), []int{3}
}

var File_proto_echo_echo_proto protoreflect.FileDescriptor

const file_proto_echo_echo_proto_rawDesc = "" +
	"\n" +
	"\x15proto/echo/echo.proto\x12\x04echo\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\x0f\n" +
	"\rChargeRequest\"\x10\n" +
	"\x0eChargeResponse\"\x12\n" +
	"\x10DischargeRequest\"\x13\n" +
	"\x11DischargeResponse2\xb2\x01\n" +
	"\x04Echo\x12N\n" +
	"\x06Charge\x12\x13.echo.ChargeRequest\x1a\x14.echo.ChargeResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/charge\x12Z\n" +
	"\tDischarge\x12\x16.echo.DischargeRequest\x1a\x17.echo.DischargeResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/dischargeB\x0eZ\fecho/api;apib\x06proto3"

var (
	file_proto_echo_echo_proto_rawDescOnce sync.Once
	file_proto_echo_echo_proto_rawDescData []byte
)

func file_proto_echo_echo_proto_rawDescGZIP() []byte {
	file_proto_echo_echo_proto_rawDescOnce.Do(func() {
		file_proto_echo_echo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_echo_echo_proto_rawDesc), len(file_proto_echo_echo_proto_rawDesc)))
	})
	return file_proto_echo_echo_proto_rawDescData
}

var file_proto_echo_echo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_echo_echo_proto_goTypes = []any{
	(*ChargeRequest)(nil),     // 0: echo.ChargeRequest
	(*ChargeResponse)(nil),    // 1: echo.ChargeResponse
	(*DischargeRequest)(nil),  // 2: echo.DischargeRequest
	(*DischargeResponse)(nil), // 3: echo.DischargeResponse
}
var file_proto_echo_echo_proto_depIdxs = []int32{
	0, // 0: echo.Echo.Charge:input_type -> echo.ChargeRequest
	2, // 1: echo.Echo.Discharge:input_type -> echo.DischargeRequest
	1, // 2: echo.Echo.Charge:output_type -> echo.ChargeResponse
	3, // 3: echo.Echo.Discharge:output_type -> echo.DischargeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_echo_echo_proto_init() }
func file_proto_echo_echo_proto_init() {
	if File_proto_echo_echo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_echo_echo_proto_rawDesc), len(file_proto_echo_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_echo_echo_proto_goTypes,
		DependencyIndexes: file_proto_echo_echo_proto_depIdxs,
		MessageInfos:      file_proto_echo_echo_proto_msgTypes,
	}.Build()
	File_proto_echo_echo_proto = out.File
	file_proto_echo_echo_proto_goTypes = nil
	file_proto_echo_echo_proto_depIdxs = nil
}
