// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/acoustics/acoustics.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Acoustics_Entry_FullMethodName = "/acoustics.Acoustics/Entry"
)

// AcousticsClient is the client API for Acoustics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Acoustics ...
type AcousticsClient interface {
	Entry(ctx context.Context, in *EntryRequest, opts ...grpc.CallOption) (*EntryResponse, error)
}

type acousticsClient struct {
	cc grpc.ClientConnInterface
}

func NewAcousticsClient(cc grpc.ClientConnInterface) AcousticsClient {
	return &acousticsClient{cc}
}

func (c *acousticsClient) Entry(ctx context.Context, in *EntryRequest, opts ...grpc.CallOption) (*EntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntryResponse)
	err := c.cc.Invoke(ctx, Acoustics_Entry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AcousticsServer is the server API for Acoustics service.
// All implementations must embed UnimplementedAcousticsServer
// for forward compatibility.
//
// Acoustics ...
type AcousticsServer interface {
	Entry(context.Context, *EntryRequest) (*EntryResponse, error)
	mustEmbedUnimplementedAcousticsServer()
}

// UnimplementedAcousticsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAcousticsServer struct{}

func (UnimplementedAcousticsServer) Entry(context.Context, *EntryRequest) (*EntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Entry not implemented")
}
func (UnimplementedAcousticsServer) mustEmbedUnimplementedAcousticsServer() {}
func (UnimplementedAcousticsServer) testEmbeddedByValue()                   {}

// UnsafeAcousticsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AcousticsServer will
// result in compilation errors.
type UnsafeAcousticsServer interface {
	mustEmbedUnimplementedAcousticsServer()
}

func RegisterAcousticsServer(s grpc.ServiceRegistrar, srv AcousticsServer) {
	// If the following call panics, it indicates UnimplementedAcousticsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Acoustics_ServiceDesc, srv)
}

func _Acoustics_Entry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AcousticsServer).Entry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Acoustics_Entry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AcousticsServer).Entry(ctx, req.(*EntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Acoustics_ServiceDesc is the grpc.ServiceDesc for Acoustics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Acoustics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "acoustics.Acoustics",
	HandlerType: (*AcousticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Entry",
			Handler:    _Acoustics_Entry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/acoustics/acoustics.proto",
}
