// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/acoustics/acoustics.proto

package api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryRequest) Reset() {
	*x = EntryRequest{}
	mi := &file_proto_acoustics_acoustics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryRequest) ProtoMessage() {}

func (x *EntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acoustics_acoustics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryRequest.ProtoReflect.Descriptor instead.
func (*EntryRequest) Descriptor() ([]byte, []int) {
	return file_proto_acoustics_acoustics_proto_rawDescGZIP(), []int{0}
}

type EntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryResponse) Reset() {
	*x = EntryResponse{}
	mi := &file_proto_acoustics_acoustics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryResponse) ProtoMessage() {}

func (x *EntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_acoustics_acoustics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryResponse.ProtoReflect.Descriptor instead.
func (*EntryResponse) Descriptor() ([]byte, []int) {
	return file_proto_acoustics_acoustics_proto_rawDescGZIP(), []int{1}
}

var File_proto_acoustics_acoustics_proto protoreflect.FileDescriptor

const file_proto_acoustics_acoustics_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/acoustics/acoustics.proto\x12\tacoustics\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\x0e\n" +
	"\fEntryRequest\"\x0f\n" +
	"\rEntryResponse2a\n" +
	"\tAcoustics\x12T\n" +
	"\x05Entry\x12\x17.acoustics.EntryRequest\x1a\x18.acoustics.EntryResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/api/v1/entryB\x13Z\x11acoustics/api;apib\x06proto3"

var (
	file_proto_acoustics_acoustics_proto_rawDescOnce sync.Once
	file_proto_acoustics_acoustics_proto_rawDescData []byte
)

func file_proto_acoustics_acoustics_proto_rawDescGZIP() []byte {
	file_proto_acoustics_acoustics_proto_rawDescOnce.Do(func() {
		file_proto_acoustics_acoustics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_acoustics_acoustics_proto_rawDesc), len(file_proto_acoustics_acoustics_proto_rawDesc)))
	})
	return file_proto_acoustics_acoustics_proto_rawDescData
}

var file_proto_acoustics_acoustics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_acoustics_acoustics_proto_goTypes = []any{
	(*EntryRequest)(nil),  // 0: acoustics.EntryRequest
	(*EntryResponse)(nil), // 1: acoustics.EntryResponse
}
var file_proto_acoustics_acoustics_proto_depIdxs = []int32{
	0, // 0: acoustics.Acoustics.Entry:input_type -> acoustics.EntryRequest
	1, // 1: acoustics.Acoustics.Entry:output_type -> acoustics.EntryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_acoustics_acoustics_proto_init() }
func file_proto_acoustics_acoustics_proto_init() {
	if File_proto_acoustics_acoustics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_acoustics_acoustics_proto_rawDesc), len(file_proto_acoustics_acoustics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_acoustics_acoustics_proto_goTypes,
		DependencyIndexes: file_proto_acoustics_acoustics_proto_depIdxs,
		MessageInfos:      file_proto_acoustics_acoustics_proto_msgTypes,
	}.Build()
	File_proto_acoustics_acoustics_proto = out.File
	file_proto_acoustics_acoustics_proto_goTypes = nil
	file_proto_acoustics_acoustics_proto_depIdxs = nil
}
