// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/rate_limiter/rate_limiter.proto

package api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServeTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeTokensRequest) Reset() {
	*x = ServeTokensRequest{}
	mi := &file_proto_rate_limiter_rate_limiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeTokensRequest) ProtoMessage() {}

func (x *ServeTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rate_limiter_rate_limiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeTokensRequest.ProtoReflect.Descriptor instead.
func (*ServeTokensRequest) Descriptor() ([]byte, []int) {
	return file_proto_rate_limiter_rate_limiter_proto_rawDescGZIP(), []int{0}
}

func (x *ServeTokensRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ServeTokensRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ServeTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantity      int32                  `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Rps           float32                `protobuf:"fixed32,2,opt,name=rps,proto3" json:"rps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServeTokensResponse) Reset() {
	*x = ServeTokensResponse{}
	mi := &file_proto_rate_limiter_rate_limiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServeTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServeTokensResponse) ProtoMessage() {}

func (x *ServeTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rate_limiter_rate_limiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServeTokensResponse.ProtoReflect.Descriptor instead.
func (*ServeTokensResponse) Descriptor() ([]byte, []int) {
	return file_proto_rate_limiter_rate_limiter_proto_rawDescGZIP(), []int{1}
}

func (x *ServeTokensResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ServeTokensResponse) GetRps() float32 {
	if x != nil {
		return x.Rps
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_rate_limiter_rate_limiter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rate_limiter_rate_limiter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_rate_limiter_rate_limiter_proto_rawDescGZIP(), []int{2}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderIp      string                 `protobuf:"bytes,1,opt,name=leader_ip,json=leaderIp,proto3" json:"leader_ip,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Rps           float32                `protobuf:"fixed32,3,opt,name=rps,proto3" json:"rps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_rate_limiter_rate_limiter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rate_limiter_rate_limiter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_rate_limiter_rate_limiter_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetLeaderIp() string {
	if x != nil {
		return x.LeaderIp
	}
	return ""
}

func (x *StatusResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *StatusResponse) GetRps() float32 {
	if x != nil {
		return x.Rps
	}
	return 0
}

var File_proto_rate_limiter_rate_limiter_proto protoreflect.FileDescriptor

const file_proto_rate_limiter_rate_limiter_proto_rawDesc = "" +
	"\n" +
	"%proto/rate_limiter/rate_limiter.proto\x12\frate_limiter\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"@\n" +
	"\x12ServeTokensRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"C\n" +
	"\x13ServeTokensResponse\x12\x1a\n" +
	"\bquantity\x18\x01 \x01(\x05R\bquantity\x12\x10\n" +
	"\x03rps\x18\x02 \x01(\x02R\x03rps\"\x0f\n" +
	"\rStatusRequest\"O\n" +
	"\x0eStatusResponse\x12\x1b\n" +
	"\tleader_ip\x18\x01 \x01(\tR\bleaderIp\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x10\n" +
	"\x03rps\x18\x03 \x01(\x02R\x03rps2\xd9\x01\n" +
	"\vRateLimiter\x12m\n" +
	"\vServeTokens\x12 .rate_limiter.ServeTokensRequest\x1a!.rate_limiter.ServeTokensResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/tokens\x12[\n" +
	"\x06Status\x12\x1b.rate_limiter.StatusRequest\x1a\x1c.rate_limiter.StatusResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/statusB\x16Z\x14rate_limiter/api;apib\x06proto3"

var (
	file_proto_rate_limiter_rate_limiter_proto_rawDescOnce sync.Once
	file_proto_rate_limiter_rate_limiter_proto_rawDescData []byte
)

func file_proto_rate_limiter_rate_limiter_proto_rawDescGZIP() []byte {
	file_proto_rate_limiter_rate_limiter_proto_rawDescOnce.Do(func() {
		file_proto_rate_limiter_rate_limiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rate_limiter_rate_limiter_proto_rawDesc), len(file_proto_rate_limiter_rate_limiter_proto_rawDesc)))
	})
	return file_proto_rate_limiter_rate_limiter_proto_rawDescData
}

var file_proto_rate_limiter_rate_limiter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_rate_limiter_rate_limiter_proto_goTypes = []any{
	(*ServeTokensRequest)(nil),  // 0: rate_limiter.ServeTokensRequest
	(*ServeTokensResponse)(nil), // 1: rate_limiter.ServeTokensResponse
	(*StatusRequest)(nil),       // 2: rate_limiter.StatusRequest
	(*StatusResponse)(nil),      // 3: rate_limiter.StatusResponse
}
var file_proto_rate_limiter_rate_limiter_proto_depIdxs = []int32{
	0, // 0: rate_limiter.RateLimiter.ServeTokens:input_type -> rate_limiter.ServeTokensRequest
	2, // 1: rate_limiter.RateLimiter.Status:input_type -> rate_limiter.StatusRequest
	1, // 2: rate_limiter.RateLimiter.ServeTokens:output_type -> rate_limiter.ServeTokensResponse
	3, // 3: rate_limiter.RateLimiter.Status:output_type -> rate_limiter.StatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rate_limiter_rate_limiter_proto_init() }
func file_proto_rate_limiter_rate_limiter_proto_init() {
	if File_proto_rate_limiter_rate_limiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rate_limiter_rate_limiter_proto_rawDesc), len(file_proto_rate_limiter_rate_limiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rate_limiter_rate_limiter_proto_goTypes,
		DependencyIndexes: file_proto_rate_limiter_rate_limiter_proto_depIdxs,
		MessageInfos:      file_proto_rate_limiter_rate_limiter_proto_msgTypes,
	}.Build()
	File_proto_rate_limiter_rate_limiter_proto = out.File
	file_proto_rate_limiter_rate_limiter_proto_goTypes = nil
	file_proto_rate_limiter_rate_limiter_proto_depIdxs = nil
}
