// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/orchestrator/orchestrator.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on EntryRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EntryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EntryRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EntryRequestMultiError, or
// nil if none found.
func (m *EntryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *EntryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CurrentSession

	// no validation rules for PreviousSession

	if len(errors) > 0 {
		return EntryRequestMultiError(errors)
	}

	return nil
}

// EntryRequestMultiError is an error wrapping multiple validation errors
// returned by EntryRequest.ValidateAll() if the designated constraints aren't met.
type EntryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EntryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EntryRequestMultiError) AllErrors() []error { return m }

// EntryRequestValidationError is the validation error returned by
// EntryRequest.Validate if the designated constraints aren't met.
type EntryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EntryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EntryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EntryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EntryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EntryRequestValidationError) ErrorName() string { return "EntryRequestValidationError" }

// Error satisfies the builtin error interface
func (e EntryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEntryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EntryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EntryRequestValidationError{}

// Validate checks the field values on EntryResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *EntryResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on EntryResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in EntryResponseMultiError, or
// nil if none found.
func (m *EntryResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *EntryResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	// no validation rules for Data

	if len(errors) > 0 {
		return EntryResponseMultiError(errors)
	}

	return nil
}

// EntryResponseMultiError is an error wrapping multiple validation errors
// returned by EntryResponse.ValidateAll() if the designated constraints
// aren't met.
type EntryResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m EntryResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m EntryResponseMultiError) AllErrors() []error { return m }

// EntryResponseValidationError is the validation error returned by
// EntryResponse.Validate if the designated constraints aren't met.
type EntryResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e EntryResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e EntryResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e EntryResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e EntryResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e EntryResponseValidationError) ErrorName() string { return "EntryResponseValidationError" }

// Error satisfies the builtin error interface
func (e EntryResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sEntryResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = EntryResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = EntryResponseValidationError{}
