// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: proto/orchestrator/prototypes.proto

package prototypes

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enums
type MessageType int32

const (
	MessageType_TEXT     MessageType = 0
	MessageType_IMAGE    MessageType = 1
	MessageType_VIDEO    MessageType = 2
	MessageType_AUDIO    MessageType = 3
	MessageType_FILE     MessageType = 4
	MessageType_LOCATION MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "TEXT",
		1: "IMAGE",
		2: "VIDEO",
		3: "AUDIO",
		4: "FILE",
		5: "LOCATION",
	}
	MessageType_value = map[string]int32{
		"TEXT":     0,
		"IMAGE":    1,
		"VIDEO":    2,
		"AUDIO":    3,
		"FILE":     4,
		"LOCATION": 5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orchestrator_prototypes_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_orchestrator_prototypes_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_orchestrator_prototypes_proto_rawDescGZIP(), []int{0}
}

type MessageStatus int32

const (
	MessageStatus_SENT      MessageStatus = 0
	MessageStatus_DELIVERED MessageStatus = 1
	MessageStatus_READ      MessageStatus = 2
	MessageStatus_FAILED    MessageStatus = 3
)

// Enum value maps for MessageStatus.
var (
	MessageStatus_name = map[int32]string{
		0: "SENT",
		1: "DELIVERED",
		2: "READ",
		3: "FAILED",
	}
	MessageStatus_value = map[string]int32{
		"SENT":      0,
		"DELIVERED": 1,
		"READ":      2,
		"FAILED":    3,
	}
)

func (x MessageStatus) Enum() *MessageStatus {
	p := new(MessageStatus)
	*p = x
	return p
}

func (x MessageStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orchestrator_prototypes_proto_enumTypes[1].Descriptor()
}

func (MessageStatus) Type() protoreflect.EnumType {
	return &file_proto_orchestrator_prototypes_proto_enumTypes[1]
}

func (x MessageStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageStatus.Descriptor instead.
func (MessageStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_orchestrator_prototypes_proto_rawDescGZIP(), []int{1}
}

// Message ...
type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	FromUserId     string                 `protobuf:"bytes,2,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId       string                 `protobuf:"bytes,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Type           MessageType            `protobuf:"varint,5,opt,name=type,proto3,enum=orchestrator.MessageType" json:"type,omitempty"`
	Timestamp      int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status         MessageStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=orchestrator.MessageStatus" json:"status,omitempty"`
	ConversationId string                 `protobuf:"bytes,8,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // optional, for group chats
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_orchestrator_prototypes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_prototypes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_prototypes_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *Message) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_TEXT
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_SENT
}

func (x *Message) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

var File_proto_orchestrator_prototypes_proto protoreflect.FileDescriptor

const file_proto_orchestrator_prototypes_proto_rawDesc = "" +
	"\n" +
	"#proto/orchestrator/prototypes.proto\x12\forchestrator\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xad\x02\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12 \n" +
	"\ffrom_user_id\x18\x02 \x01(\tR\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x03 \x01(\tR\btoUserId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12-\n" +
	"\x04type\x18\x05 \x01(\x0e2\x19.orchestrator.MessageTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x123\n" +
	"\x06status\x18\a \x01(\x0e2\x1b.orchestrator.MessageStatusR\x06status\x12'\n" +
	"\x0fconversation_id\x18\b \x01(\tR\x0econversationId*P\n" +
	"\vMessageType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\t\n" +
	"\x05VIDEO\x10\x02\x12\t\n" +
	"\x05AUDIO\x10\x03\x12\b\n" +
	"\x04FILE\x10\x04\x12\f\n" +
	"\bLOCATION\x10\x05*>\n" +
	"\rMessageStatus\x12\b\n" +
	"\x04SENT\x10\x00\x12\r\n" +
	"\tDELIVERED\x10\x01\x12\b\n" +
	"\x04READ\x10\x02\x12\n" +
	"\n" +
	"\x06FAILED\x10\x03B\x19Z\x17orchestrator/prototypesb\x06proto3"

var (
	file_proto_orchestrator_prototypes_proto_rawDescOnce sync.Once
	file_proto_orchestrator_prototypes_proto_rawDescData []byte
)

func file_proto_orchestrator_prototypes_proto_rawDescGZIP() []byte {
	file_proto_orchestrator_prototypes_proto_rawDescOnce.Do(func() {
		file_proto_orchestrator_prototypes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orchestrator_prototypes_proto_rawDesc), len(file_proto_orchestrator_prototypes_proto_rawDesc)))
	})
	return file_proto_orchestrator_prototypes_proto_rawDescData
}

var file_proto_orchestrator_prototypes_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_orchestrator_prototypes_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_orchestrator_prototypes_proto_goTypes = []any{
	(MessageType)(0),   // 0: orchestrator.MessageType
	(MessageStatus)(0), // 1: orchestrator.MessageStatus
	(*Message)(nil),    // 2: orchestrator.Message
}
var file_proto_orchestrator_prototypes_proto_depIdxs = []int32{
	0, // 0: orchestrator.Message.type:type_name -> orchestrator.MessageType
	1, // 1: orchestrator.Message.status:type_name -> orchestrator.MessageStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_orchestrator_prototypes_proto_init() }
func file_proto_orchestrator_prototypes_proto_init() {
	if File_proto_orchestrator_prototypes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orchestrator_prototypes_proto_rawDesc), len(file_proto_orchestrator_prototypes_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_orchestrator_prototypes_proto_goTypes,
		DependencyIndexes: file_proto_orchestrator_prototypes_proto_depIdxs,
		EnumInfos:         file_proto_orchestrator_prototypes_proto_enumTypes,
		MessageInfos:      file_proto_orchestrator_prototypes_proto_msgTypes,
	}.Build()
	File_proto_orchestrator_prototypes_proto = out.File
	file_proto_orchestrator_prototypes_proto_goTypes = nil
	file_proto_orchestrator_prototypes_proto_depIdxs = nil
}
