// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/orchestrator/receiver.proto

package api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SendMessage request
type SendMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Sender         string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	ConversationId int64                  `protobuf:"varint,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Type           MessageType            `protobuf:"varint,4,opt,name=type,proto3,enum=orchestrator.MessageType" json:"type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_orchestrator_receiver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_receiver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_receiver_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SendMessageRequest) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_TEXT
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *MessageData           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_proto_orchestrator_receiver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_receiver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_receiver_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMessageResponse) GetData() *MessageData {
	if x != nil {
		return x.Data
	}
	return nil
}

type MessageData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        MessageStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=orchestrator.MessageStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageData) Reset() {
	*x = MessageData{}
	mi := &file_proto_orchestrator_receiver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageData) ProtoMessage() {}

func (x *MessageData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orchestrator_receiver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageData.ProtoReflect.Descriptor instead.
func (*MessageData) Descriptor() ([]byte, []int) {
	return file_proto_orchestrator_receiver_proto_rawDescGZIP(), []int{2}
}

func (x *MessageData) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MessageData) GetStatus() MessageStatus {
	if x != nil {
		return x.Status
	}
	return MessageStatus_SENT
}

var File_proto_orchestrator_receiver_proto protoreflect.FileDescriptor

const file_proto_orchestrator_receiver_proto_rawDesc = "" +
	"\n" +
	"!proto/orchestrator/receiver.proto\x12\forchestrator\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a#proto/orchestrator/prototypes.proto\"\xb0\x01\n" +
	"\x12SendMessageRequest\x12\x1f\n" +
	"\x06sender\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06sender\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\x03R\x0econversationId\x12!\n" +
	"\acontent\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\acontent\x12-\n" +
	"\x04type\x18\x04 \x01(\x0e2\x19.orchestrator.MessageTypeR\x04type\"r\n" +
	"\x13SendMessageResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x03 \x01(\v2\x19.orchestrator.MessageDataR\x04data\"\x7f\n" +
	"\vMessageData\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x123\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1b.orchestrator.MessageStatusR\x06status2{\n" +
	"\bReceiver\x12o\n" +
	"\vSendMessage\x12 .orchestrator.SendMessageRequest\x1a!.orchestrator.SendMessageResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/messagesB\x16Z\x14orchestrator/api;apib\x06proto3"

var (
	file_proto_orchestrator_receiver_proto_rawDescOnce sync.Once
	file_proto_orchestrator_receiver_proto_rawDescData []byte
)

func file_proto_orchestrator_receiver_proto_rawDescGZIP() []byte {
	file_proto_orchestrator_receiver_proto_rawDescOnce.Do(func() {
		file_proto_orchestrator_receiver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orchestrator_receiver_proto_rawDesc), len(file_proto_orchestrator_receiver_proto_rawDesc)))
	})
	return file_proto_orchestrator_receiver_proto_rawDescData
}

var file_proto_orchestrator_receiver_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_orchestrator_receiver_proto_goTypes = []any{
	(*SendMessageRequest)(nil),  // 0: orchestrator.SendMessageRequest
	(*SendMessageResponse)(nil), // 1: orchestrator.SendMessageResponse
	(*MessageData)(nil),         // 2: orchestrator.MessageData
	(MessageType)(0),            // 3: orchestrator.MessageType
	(MessageStatus)(0),          // 4: orchestrator.MessageStatus
}
var file_proto_orchestrator_receiver_proto_depIdxs = []int32{
	3, // 0: orchestrator.SendMessageRequest.type:type_name -> orchestrator.MessageType
	2, // 1: orchestrator.SendMessageResponse.data:type_name -> orchestrator.MessageData
	4, // 2: orchestrator.MessageData.status:type_name -> orchestrator.MessageStatus
	0, // 3: orchestrator.Receiver.SendMessage:input_type -> orchestrator.SendMessageRequest
	1, // 4: orchestrator.Receiver.SendMessage:output_type -> orchestrator.SendMessageResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_orchestrator_receiver_proto_init() }
func file_proto_orchestrator_receiver_proto_init() {
	if File_proto_orchestrator_receiver_proto != nil {
		return
	}
	file_proto_orchestrator_prototypes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orchestrator_receiver_proto_rawDesc), len(file_proto_orchestrator_receiver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orchestrator_receiver_proto_goTypes,
		DependencyIndexes: file_proto_orchestrator_receiver_proto_depIdxs,
		MessageInfos:      file_proto_orchestrator_receiver_proto_msgTypes,
	}.Build()
	File_proto_orchestrator_receiver_proto = out.File
	file_proto_orchestrator_receiver_proto_goTypes = nil
	file_proto_orchestrator_receiver_proto_depIdxs = nil
}
