// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/orchestrator/streamer.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ReceiveMessagesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReceiveMessagesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReceiveMessagesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReceiveMessagesRequestMultiError, or nil if none found.
func (m *ReceiveMessagesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReceiveMessagesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetUserIdentification()) < 1 {
		err := ReceiveMessagesRequestValidationError{
			field:  "UserIdentification",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ReceiveMessagesRequestMultiError(errors)
	}

	return nil
}

// ReceiveMessagesRequestMultiError is an error wrapping multiple validation
// errors returned by ReceiveMessagesRequest.ValidateAll() if the designated
// constraints aren't met.
type ReceiveMessagesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReceiveMessagesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReceiveMessagesRequestMultiError) AllErrors() []error { return m }

// ReceiveMessagesRequestValidationError is the validation error returned by
// ReceiveMessagesRequest.Validate if the designated constraints aren't met.
type ReceiveMessagesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReceiveMessagesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReceiveMessagesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReceiveMessagesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReceiveMessagesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReceiveMessagesRequestValidationError) ErrorName() string {
	return "ReceiveMessagesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ReceiveMessagesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReceiveMessagesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReceiveMessagesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReceiveMessagesRequestValidationError{}
