// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: proto/authenticator/authenticator.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on InitSignUpRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *InitSignUpRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InitSignUpRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// InitSignUpRequestMultiError, or nil if none found.
func (m *InitSignUpRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *InitSignUpRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Phone

	if len(errors) > 0 {
		return InitSignUpRequestMultiError(errors)
	}

	return nil
}

// InitSignUpRequestMultiError is an error wrapping multiple validation errors
// returned by InitSignUpRequest.ValidateAll() if the designated constraints
// aren't met.
type InitSignUpRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InitSignUpRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InitSignUpRequestMultiError) AllErrors() []error { return m }

// InitSignUpRequestValidationError is the validation error returned by
// InitSignUpRequest.Validate if the designated constraints aren't met.
type InitSignUpRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InitSignUpRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InitSignUpRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InitSignUpRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InitSignUpRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InitSignUpRequestValidationError) ErrorName() string {
	return "InitSignUpRequestValidationError"
}

// Error satisfies the builtin error interface
func (e InitSignUpRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInitSignUpRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InitSignUpRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InitSignUpRequestValidationError{}

// Validate checks the field values on InitSignUpResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *InitSignUpResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InitSignUpResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// InitSignUpResponseMultiError, or nil if none found.
func (m *InitSignUpResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *InitSignUpResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if len(errors) > 0 {
		return InitSignUpResponseMultiError(errors)
	}

	return nil
}

// InitSignUpResponseMultiError is an error wrapping multiple validation errors
// returned by InitSignUpResponse.ValidateAll() if the designated constraints
// aren't met.
type InitSignUpResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InitSignUpResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InitSignUpResponseMultiError) AllErrors() []error { return m }

// InitSignUpResponseValidationError is the validation error returned by
// InitSignUpResponse.Validate if the designated constraints aren't met.
type InitSignUpResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InitSignUpResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InitSignUpResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InitSignUpResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InitSignUpResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InitSignUpResponseValidationError) ErrorName() string {
	return "InitSignUpResponseValidationError"
}

// Error satisfies the builtin error interface
func (e InitSignUpResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInitSignUpResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InitSignUpResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InitSignUpResponseValidationError{}

// Validate checks the field values on SignUpRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SignUpRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SignUpRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SignUpRequestMultiError, or
// nil if none found.
func (m *SignUpRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SignUpRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FlowId

	// no validation rules for Otp

	if len(errors) > 0 {
		return SignUpRequestMultiError(errors)
	}

	return nil
}

// SignUpRequestMultiError is an error wrapping multiple validation errors
// returned by SignUpRequest.ValidateAll() if the designated constraints
// aren't met.
type SignUpRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SignUpRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SignUpRequestMultiError) AllErrors() []error { return m }

// SignUpRequestValidationError is the validation error returned by
// SignUpRequest.Validate if the designated constraints aren't met.
type SignUpRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SignUpRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SignUpRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SignUpRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SignUpRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SignUpRequestValidationError) ErrorName() string { return "SignUpRequestValidationError" }

// Error satisfies the builtin error interface
func (e SignUpRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSignUpRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SignUpRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SignUpRequestValidationError{}

// Validate checks the field values on SignUpResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SignUpResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SignUpResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SignUpResponseMultiError,
// or nil if none found.
func (m *SignUpResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SignUpResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SignUpResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SignUpResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SignUpResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SignUpResponseMultiError(errors)
	}

	return nil
}

// SignUpResponseMultiError is an error wrapping multiple validation errors
// returned by SignUpResponse.ValidateAll() if the designated constraints
// aren't met.
type SignUpResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SignUpResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SignUpResponseMultiError) AllErrors() []error { return m }

// SignUpResponseValidationError is the validation error returned by
// SignUpResponse.Validate if the designated constraints aren't met.
type SignUpResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SignUpResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SignUpResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SignUpResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SignUpResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SignUpResponseValidationError) ErrorName() string { return "SignUpResponseValidationError" }

// Error satisfies the builtin error interface
func (e SignUpResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSignUpResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SignUpResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SignUpResponseValidationError{}

// Validate checks the field values on InitFacebookLoginRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *InitFacebookLoginRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InitFacebookLoginRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// InitFacebookLoginRequestMultiError, or nil if none found.
func (m *InitFacebookLoginRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *InitFacebookLoginRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return InitFacebookLoginRequestMultiError(errors)
	}

	return nil
}

// InitFacebookLoginRequestMultiError is an error wrapping multiple validation
// errors returned by InitFacebookLoginRequest.ValidateAll() if the designated
// constraints aren't met.
type InitFacebookLoginRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InitFacebookLoginRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InitFacebookLoginRequestMultiError) AllErrors() []error { return m }

// InitFacebookLoginRequestValidationError is the validation error returned by
// InitFacebookLoginRequest.Validate if the designated constraints aren't met.
type InitFacebookLoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InitFacebookLoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InitFacebookLoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InitFacebookLoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InitFacebookLoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InitFacebookLoginRequestValidationError) ErrorName() string {
	return "InitFacebookLoginRequestValidationError"
}

// Error satisfies the builtin error interface
func (e InitFacebookLoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInitFacebookLoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InitFacebookLoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InitFacebookLoginRequestValidationError{}

// Validate checks the field values on InitFacebookLoginResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *InitFacebookLoginResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InitFacebookLoginResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// InitFacebookLoginResponseMultiError, or nil if none found.
func (m *InitFacebookLoginResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *InitFacebookLoginResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InitFacebookLoginResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InitFacebookLoginResponseValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InitFacebookLoginResponseValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return InitFacebookLoginResponseMultiError(errors)
	}

	return nil
}

// InitFacebookLoginResponseMultiError is an error wrapping multiple validation
// errors returned by InitFacebookLoginResponse.ValidateAll() if the
// designated constraints aren't met.
type InitFacebookLoginResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InitFacebookLoginResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InitFacebookLoginResponseMultiError) AllErrors() []error { return m }

// InitFacebookLoginResponseValidationError is the validation error returned by
// InitFacebookLoginResponse.Validate if the designated constraints aren't met.
type InitFacebookLoginResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InitFacebookLoginResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InitFacebookLoginResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InitFacebookLoginResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InitFacebookLoginResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InitFacebookLoginResponseValidationError) ErrorName() string {
	return "InitFacebookLoginResponseValidationError"
}

// Error satisfies the builtin error interface
func (e InitFacebookLoginResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInitFacebookLoginResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InitFacebookLoginResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InitFacebookLoginResponseValidationError{}

// Validate checks the field values on InitSignUpResponse_Data with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *InitSignUpResponse_Data) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InitSignUpResponse_Data with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// InitSignUpResponse_DataMultiError, or nil if none found.
func (m *InitSignUpResponse_Data) ValidateAll() error {
	return m.validate(true)
}

func (m *InitSignUpResponse_Data) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FlowId

	if len(errors) > 0 {
		return InitSignUpResponse_DataMultiError(errors)
	}

	return nil
}

// InitSignUpResponse_DataMultiError is an error wrapping multiple validation
// errors returned by InitSignUpResponse_Data.ValidateAll() if the designated
// constraints aren't met.
type InitSignUpResponse_DataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InitSignUpResponse_DataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InitSignUpResponse_DataMultiError) AllErrors() []error { return m }

// InitSignUpResponse_DataValidationError is the validation error returned by
// InitSignUpResponse_Data.Validate if the designated constraints aren't met.
type InitSignUpResponse_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InitSignUpResponse_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InitSignUpResponse_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InitSignUpResponse_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InitSignUpResponse_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InitSignUpResponse_DataValidationError) ErrorName() string {
	return "InitSignUpResponse_DataValidationError"
}

// Error satisfies the builtin error interface
func (e InitSignUpResponse_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInitSignUpResponse_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InitSignUpResponse_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InitSignUpResponse_DataValidationError{}

// Validate checks the field values on SignUpResponse_Data with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SignUpResponse_Data) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SignUpResponse_Data with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SignUpResponse_DataMultiError, or nil if none found.
func (m *SignUpResponse_Data) ValidateAll() error {
	return m.validate(true)
}

func (m *SignUpResponse_Data) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	if len(errors) > 0 {
		return SignUpResponse_DataMultiError(errors)
	}

	return nil
}

// SignUpResponse_DataMultiError is an error wrapping multiple validation
// errors returned by SignUpResponse_Data.ValidateAll() if the designated
// constraints aren't met.
type SignUpResponse_DataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SignUpResponse_DataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SignUpResponse_DataMultiError) AllErrors() []error { return m }

// SignUpResponse_DataValidationError is the validation error returned by
// SignUpResponse_Data.Validate if the designated constraints aren't met.
type SignUpResponse_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SignUpResponse_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SignUpResponse_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SignUpResponse_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SignUpResponse_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SignUpResponse_DataValidationError) ErrorName() string {
	return "SignUpResponse_DataValidationError"
}

// Error satisfies the builtin error interface
func (e SignUpResponse_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSignUpResponse_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SignUpResponse_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SignUpResponse_DataValidationError{}

// Validate checks the field values on InitFacebookLoginResponse_Data with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *InitFacebookLoginResponse_Data) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InitFacebookLoginResponse_Data with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// InitFacebookLoginResponse_DataMultiError, or nil if none found.
func (m *InitFacebookLoginResponse_Data) ValidateAll() error {
	return m.validate(true)
}

func (m *InitFacebookLoginResponse_Data) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RedirectUrl

	if len(errors) > 0 {
		return InitFacebookLoginResponse_DataMultiError(errors)
	}

	return nil
}

// InitFacebookLoginResponse_DataMultiError is an error wrapping multiple
// validation errors returned by InitFacebookLoginResponse_Data.ValidateAll()
// if the designated constraints aren't met.
type InitFacebookLoginResponse_DataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InitFacebookLoginResponse_DataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InitFacebookLoginResponse_DataMultiError) AllErrors() []error { return m }

// InitFacebookLoginResponse_DataValidationError is the validation error
// returned by InitFacebookLoginResponse_Data.Validate if the designated
// constraints aren't met.
type InitFacebookLoginResponse_DataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InitFacebookLoginResponse_DataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InitFacebookLoginResponse_DataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InitFacebookLoginResponse_DataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InitFacebookLoginResponse_DataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InitFacebookLoginResponse_DataValidationError) ErrorName() string {
	return "InitFacebookLoginResponse_DataValidationError"
}

// Error satisfies the builtin error interface
func (e InitFacebookLoginResponse_DataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInitFacebookLoginResponse_Data.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InitFacebookLoginResponse_DataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InitFacebookLoginResponse_DataValidationError{}
