// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/authenticator/authenticator.proto

package api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitSignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitSignUpRequest) Reset() {
	*x = InitSignUpRequest{}
	mi := &file_proto_authenticator_authenticator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSignUpRequest) ProtoMessage() {}

func (x *InitSignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authenticator_authenticator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSignUpRequest.ProtoReflect.Descriptor instead.
func (*InitSignUpRequest) Descriptor() ([]byte, []int) {
	return file_proto_authenticator_authenticator_proto_rawDescGZIP(), []int{0}
}

func (x *InitSignUpRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type InitSignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitSignUpResponse) Reset() {
	*x = InitSignUpResponse{}
	mi := &file_proto_authenticator_authenticator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSignUpResponse) ProtoMessage() {}

func (x *InitSignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authenticator_authenticator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSignUpResponse.ProtoReflect.Descriptor instead.
func (*InitSignUpResponse) Descriptor() ([]byte, []int) {
	return file_proto_authenticator_authenticator_proto_rawDescGZIP(), []int{1}
}

func (x *InitSignUpResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InitSignUpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	Otp           string                 `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_proto_authenticator_authenticator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authenticator_authenticator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_proto_authenticator_authenticator_proto_rawDescGZIP(), []int{2}
}

func (x *SignUpRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *SignUpRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type SignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *SignUpResponse_Data   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_proto_authenticator_authenticator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authenticator_authenticator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_proto_authenticator_authenticator_proto_rawDescGZIP(), []int{3}
}

func (x *SignUpResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SignUpResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignUpResponse) GetData() *SignUpResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type InitSignUpResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,3,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitSignUpResponse_Data) Reset() {
	*x = InitSignUpResponse_Data{}
	mi := &file_proto_authenticator_authenticator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSignUpResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSignUpResponse_Data) ProtoMessage() {}

func (x *InitSignUpResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authenticator_authenticator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSignUpResponse_Data.ProtoReflect.Descriptor instead.
func (*InitSignUpResponse_Data) Descriptor() ([]byte, []int) {
	return file_proto_authenticator_authenticator_proto_rawDescGZIP(), []int{1, 0}
}

func (x *InitSignUpResponse_Data) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type SignUpResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpResponse_Data) Reset() {
	*x = SignUpResponse_Data{}
	mi := &file_proto_authenticator_authenticator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse_Data) ProtoMessage() {}

func (x *SignUpResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_authenticator_authenticator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse_Data.ProtoReflect.Descriptor instead.
func (*SignUpResponse_Data) Descriptor() ([]byte, []int) {
	return file_proto_authenticator_authenticator_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SignUpResponse_Data) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_proto_authenticator_authenticator_proto protoreflect.FileDescriptor

const file_proto_authenticator_authenticator_proto_rawDesc = "" +
	"\n" +
	"'proto/authenticator/authenticator.proto\x12\rauthenticator\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\")\n" +
	"\x11InitSignUpRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"c\n" +
	"\x12InitSignUpResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x1a\x1f\n" +
	"\x04Data\x12\x17\n" +
	"\aflow_id\x18\x03 \x01(\tR\x06flowId\":\n" +
	"\rSignUpRequest\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x12\x10\n" +
	"\x03otp\x18\x02 \x01(\tR\x03otp\"\x94\x01\n" +
	"\x0eSignUpResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x04data\x18\x03 \x01(\v2\".authenticator.SignUpResponse.DataR\x04data\x1a\x1c\n" +
	"\x04Data\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token2\xe4\x01\n" +
	"\rAuthenticator\x12q\n" +
	"\n" +
	"InitSignUp\x12 .authenticator.InitSignUpRequest\x1a!.authenticator.InitSignUpResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/signup/init\x12`\n" +
	"\x06SignUp\x12\x1c.authenticator.SignUpRequest\x1a\x1d.authenticator.SignUpResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/signupB\x17Z\x15authenticator/api;apib\x06proto3"

var (
	file_proto_authenticator_authenticator_proto_rawDescOnce sync.Once
	file_proto_authenticator_authenticator_proto_rawDescData []byte
)

func file_proto_authenticator_authenticator_proto_rawDescGZIP() []byte {
	file_proto_authenticator_authenticator_proto_rawDescOnce.Do(func() {
		file_proto_authenticator_authenticator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_authenticator_authenticator_proto_rawDesc), len(file_proto_authenticator_authenticator_proto_rawDesc)))
	})
	return file_proto_authenticator_authenticator_proto_rawDescData
}

var file_proto_authenticator_authenticator_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_authenticator_authenticator_proto_goTypes = []any{
	(*InitSignUpRequest)(nil),       // 0: authenticator.InitSignUpRequest
	(*InitSignUpResponse)(nil),      // 1: authenticator.InitSignUpResponse
	(*SignUpRequest)(nil),           // 2: authenticator.SignUpRequest
	(*SignUpResponse)(nil),          // 3: authenticator.SignUpResponse
	(*InitSignUpResponse_Data)(nil), // 4: authenticator.InitSignUpResponse.Data
	(*SignUpResponse_Data)(nil),     // 5: authenticator.SignUpResponse.Data
}
var file_proto_authenticator_authenticator_proto_depIdxs = []int32{
	5, // 0: authenticator.SignUpResponse.data:type_name -> authenticator.SignUpResponse.Data
	0, // 1: authenticator.Authenticator.InitSignUp:input_type -> authenticator.InitSignUpRequest
	2, // 2: authenticator.Authenticator.SignUp:input_type -> authenticator.SignUpRequest
	1, // 3: authenticator.Authenticator.InitSignUp:output_type -> authenticator.InitSignUpResponse
	3, // 4: authenticator.Authenticator.SignUp:output_type -> authenticator.SignUpResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_authenticator_authenticator_proto_init() }
func file_proto_authenticator_authenticator_proto_init() {
	if File_proto_authenticator_authenticator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_authenticator_authenticator_proto_rawDesc), len(file_proto_authenticator_authenticator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_authenticator_authenticator_proto_goTypes,
		DependencyIndexes: file_proto_authenticator_authenticator_proto_depIdxs,
		MessageInfos:      file_proto_authenticator_authenticator_proto_msgTypes,
	}.Build()
	File_proto_authenticator_authenticator_proto = out.File
	file_proto_authenticator_authenticator_proto_goTypes = nil
	file_proto_authenticator_authenticator_proto_depIdxs = nil
}
