// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/limiter/limiter.proto

package api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CapacityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapacityRequest) Reset() {
	*x = CapacityRequest{}
	mi := &file_proto_limiter_limiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacityRequest) ProtoMessage() {}

func (x *CapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_limiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacityRequest.ProtoReflect.Descriptor instead.
func (*CapacityRequest) Descriptor() ([]byte, []int) {
	return file_proto_limiter_limiter_proto_rawDescGZIP(), []int{0}
}

func (x *CapacityRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type CapacityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rps           float64                `protobuf:"fixed64,1,opt,name=rps,proto3" json:"rps,omitempty"`
	Burst         int32                  `protobuf:"varint,2,opt,name=burst,proto3" json:"burst,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapacityResponse) Reset() {
	*x = CapacityResponse{}
	mi := &file_proto_limiter_limiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapacityResponse) ProtoMessage() {}

func (x *CapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_limiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapacityResponse.ProtoReflect.Descriptor instead.
func (*CapacityResponse) Descriptor() ([]byte, []int) {
	return file_proto_limiter_limiter_proto_rawDescGZIP(), []int{1}
}

func (x *CapacityResponse) GetRps() float64 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *CapacityResponse) GetBurst() int32 {
	if x != nil {
		return x.Burst
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_limiter_limiter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_limiter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_limiter_limiter_proto_rawDescGZIP(), []int{2}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderIp      string                 `protobuf:"bytes,1,opt,name=leader_ip,json=leaderIp,proto3" json:"leader_ip,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Rps           float32                `protobuf:"fixed32,3,opt,name=rps,proto3" json:"rps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_limiter_limiter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_limiter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_limiter_limiter_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetLeaderIp() string {
	if x != nil {
		return x.LeaderIp
	}
	return ""
}

func (x *StatusResponse) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *StatusResponse) GetRps() float32 {
	if x != nil {
		return x.Rps
	}
	return 0
}

var File_proto_limiter_limiter_proto protoreflect.FileDescriptor

const file_proto_limiter_limiter_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/limiter/limiter.proto\x12\alimiter\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"!\n" +
	"\x0fCapacityRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\":\n" +
	"\x10CapacityResponse\x12\x10\n" +
	"\x03rps\x18\x01 \x01(\x01R\x03rps\x12\x14\n" +
	"\x05burst\x18\x02 \x01(\x05R\x05burst\"\x0f\n" +
	"\rStatusRequest\"O\n" +
	"\x0eStatusResponse\x12\x1b\n" +
	"\tleader_ip\x18\x01 \x01(\tR\bleaderIp\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x10\n" +
	"\x03rps\x18\x03 \x01(\x02R\x03rps2\xba\x01\n" +
	"\aLimiter\x12\\\n" +
	"\bCapacity\x12\x18.limiter.CapacityRequest\x1a\x19.limiter.CapacityResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/capacity\x12Q\n" +
	"\x06Status\x12\x16.limiter.StatusRequest\x1a\x17.limiter.StatusResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/v1/statusB\x11Z\x0flimiter/api;apib\x06proto3"

var (
	file_proto_limiter_limiter_proto_rawDescOnce sync.Once
	file_proto_limiter_limiter_proto_rawDescData []byte
)

func file_proto_limiter_limiter_proto_rawDescGZIP() []byte {
	file_proto_limiter_limiter_proto_rawDescOnce.Do(func() {
		file_proto_limiter_limiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_limiter_limiter_proto_rawDesc), len(file_proto_limiter_limiter_proto_rawDesc)))
	})
	return file_proto_limiter_limiter_proto_rawDescData
}

var file_proto_limiter_limiter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_limiter_limiter_proto_goTypes = []any{
	(*CapacityRequest)(nil),  // 0: limiter.CapacityRequest
	(*CapacityResponse)(nil), // 1: limiter.CapacityResponse
	(*StatusRequest)(nil),    // 2: limiter.StatusRequest
	(*StatusResponse)(nil),   // 3: limiter.StatusResponse
}
var file_proto_limiter_limiter_proto_depIdxs = []int32{
	0, // 0: limiter.Limiter.Capacity:input_type -> limiter.CapacityRequest
	2, // 1: limiter.Limiter.Status:input_type -> limiter.StatusRequest
	1, // 2: limiter.Limiter.Capacity:output_type -> limiter.CapacityResponse
	3, // 3: limiter.Limiter.Status:output_type -> limiter.StatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_limiter_limiter_proto_init() }
func file_proto_limiter_limiter_proto_init() {
	if File_proto_limiter_limiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_limiter_limiter_proto_rawDesc), len(file_proto_limiter_limiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_limiter_limiter_proto_goTypes,
		DependencyIndexes: file_proto_limiter_limiter_proto_depIdxs,
		MessageInfos:      file_proto_limiter_limiter_proto_msgTypes,
	}.Build()
	File_proto_limiter_limiter_proto = out.File
	file_proto_limiter_limiter_proto_goTypes = nil
	file_proto_limiter_limiter_proto_depIdxs = nil
}
